global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mlflow-app'
    static_configs:
      - targets: ['train:9091']
    scrape_interval: 10s

  - job_name: 'lambda-metrics'
    static_configs:
      - targets: ['localhost:9091']
    scrape_interval: 30s 